name: Build and Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Get version
      id: version
      run: |
        VERSION=$($GITHUB_WORKSPACE/bin/latest-git-version)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and Package Git
      run: make package

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: git-*.pkg
        tag_name: ${{ steps.version.outputs.VERSION }}
